#!/usr/bin/env python3
"""Export StarNet/risk-aware predictor outputs as SABR safe-cap time series.

The exporter maps StarNet validation prediction windows back to the SABR
Starlink trace sessions generated by ``prepare_starlink_traces.py``.  The
resulting CSV is intentionally offline: SABR evaluation can load it once and
look up a per-trace safe throughput cap at deployment time.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import pickle
import re
import sys
import types
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd


DATASET_TO_LOC = {"chi": "us", "osn": "osn", "vic": "vic"}
LOC_TO_DATASET = {value: key for key, value in DATASET_TO_LOC.items()}
STEP_LEN = {"chi": 46, "osn": 29, "vic": 6}
PREDICTOR_SPECS = {
    "StarNet-budget-scale": {
        "summary_method": "StarNet-budget-scale",
        "array_key": "pred",
    },
    "BG-CFQS": {
        "summary_method": "BG-CFQS",
        "array_key": "pred",
    },
    "StarNet-point": {
        "summary_method": "StarNet-point",
        "array_key": "raw_pred",
        "fallback_array_key": "pred",
    },
    "XGBoost-budget-scale": {
        "summary_method": "XGBoost-budget-scale",
        "array_key": "pred",
    },
}


def install_pickle_compat() -> None:
    module = types.ModuleType("pandas.core.indexes.numeric")
    module.Int64Index = pd.Index
    module.UInt64Index = pd.Index
    module.Float64Index = pd.Index
    sys.modules["pandas.core.indexes.numeric"] = module


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="") as f:
        if not fields:
            f.write("")
            return
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def load_dataframe(path: Path) -> pd.DataFrame:
    install_pickle_compat()
    with path.open("rb") as f:
        df = pickle.load(f)
    if not isinstance(df, pd.DataFrame):
        raise TypeError(f"{path} did not contain a pandas DataFrame")
    required = {"timestamp", "throughput"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"{path} is missing required columns: {sorted(missing)}")
    df = df.copy().dropna().reset_index(drop=True)
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df["throughput"] = pd.to_numeric(df["throughput"], errors="coerce")
    df = df.dropna(subset=["timestamp", "throughput"]).reset_index(drop=True)
    return df


def split_sessions(df: pd.DataFrame, max_gap_s: float, min_len: int) -> list[pd.DataFrame]:
    work = df[["timestamp", "throughput"]].copy()
    work = work[work["throughput"] > 0].sort_values("timestamp")
    work = work.groupby("timestamp", as_index=False).agg({"throughput": "mean"})
    gaps = work["timestamp"].diff().dt.total_seconds().fillna(0)
    session_id = (gaps > max_gap_s).cumsum()
    sessions: list[pd.DataFrame] = []
    for _, part in work.groupby(session_id):
        if len(part) >= min_len:
            sessions.append(part.reset_index(drop=True))
    return sessions


def assign_split(idx: int, total: int, train_ratio: float, calib_ratio: float) -> str:
    if total == 1:
        return "train"
    train_end = max(1, int(round(total * train_ratio)))
    calib_end = max(train_end + 1, int(round(total * (train_ratio + calib_ratio))))
    if idx < train_end:
        return "train"
    if idx < min(calib_end, total):
        return "calib"
    return "test"


def timestamp_key(value) -> int:
    return int(pd.Timestamp(value).value)


def build_session_index(
    df: pd.DataFrame,
    loc: str,
    max_gap_s: float,
    min_len: int,
    train_ratio: float,
    calib_ratio: float,
) -> tuple[dict[int, dict], dict[str, dict]]:
    sessions = split_sessions(df, max_gap_s=max_gap_s, min_len=min_len)
    ts_to_meta: dict[int, dict] = {}
    trace_meta: dict[str, dict] = {}
    for idx, session in enumerate(sessions):
        split = assign_split(idx, len(sessions), train_ratio, calib_ratio)
        trace_id = f"{loc}_session_{idx:03d}.trace"
        start_ts = session["timestamp"].iloc[0]
        end_ts = session["timestamp"].iloc[-1]
        trace_meta[trace_id] = {
            "loc": loc,
            "session_idx": idx,
            "split": split,
            "points": len(session),
            "start_timestamp": str(start_ts),
            "end_timestamp": str(end_ts),
        }
        rel_t = (session["timestamp"] - start_ts).dt.total_seconds()
        for ts, rel_s in zip(session["timestamp"], rel_t):
            ts_to_meta[timestamp_key(ts)] = {
                "trace_id": trace_id,
                "session_idx": idx,
                "split": split,
                "time_s": float(rel_s),
            }
    return ts_to_meta, trace_meta


def infer_input_output_len(run_dir: str) -> tuple[int, int]:
    match = re.search(r"inlen(\d+)_outlen(\d+)", run_dir)
    if not match:
        return 75, 15
    return int(match.group(1)), int(match.group(2))


def load_run_map(summary_dir: Path) -> dict[tuple[str, str], str]:
    rows = read_csv(summary_dir / "decision_level_abr_like_main.csv")
    run_map: dict[tuple[str, str], str] = {}
    for row in rows:
        dataset = row.get("dataset", "")
        method = row.get("method", "")
        run_dir = row.get("run_dir", "")
        if dataset in DATASET_TO_LOC and method and run_dir:
            run_map[(dataset, method)] = run_dir
    return run_map


def choose_safe_cap_mbps(pred_row: np.ndarray, horizon_quantile: float) -> tuple[float, dict[str, float]]:
    values = np.asarray(pred_row, dtype=np.float64)
    values = values[np.isfinite(values)]
    if values.size == 0:
        return float("nan"), {}
    values = np.maximum(values, 0.0)
    safe = float(np.quantile(values, horizon_quantile))
    stats = {
        "horizon_pred_min_mbps": float(np.min(values)),
        "horizon_pred_p10_mbps": float(np.quantile(values, 0.10)),
        "horizon_pred_p50_mbps": float(np.quantile(values, 0.50)),
        "horizon_pred_mean_mbps": float(np.mean(values)),
        "horizon_pred_std_mbps": float(np.std(values)),
    }
    return safe, stats


def trace_file_exists(trace_root: Path, loc: str, split: str, trace_id: str) -> bool:
    return (trace_root / loc / split / trace_id).exists()


def export_predictor(
    predictor: str,
    summary_dir: Path,
    source_root: Path,
    trace_root: Path,
    horizon_quantile: float,
    splits: set[str],
    max_gap_s: float,
    min_len: int,
    train_ratio: float,
    calib_ratio: float,
) -> tuple[list[dict], list[dict]]:
    if predictor not in PREDICTOR_SPECS:
        raise ValueError(f"Unknown predictor: {predictor}")
    spec = PREDICTOR_SPECS[predictor]
    run_map = load_run_map(summary_dir)
    rows: list[dict] = []
    summary_rows: list[dict] = []

    for dataset, loc in DATASET_TO_LOC.items():
        run_dir = run_map.get((dataset, spec["summary_method"]))
        if not run_dir:
            raise FileNotFoundError(f"No run_dir found for {dataset}/{spec['summary_method']}")
        pred_path = Path(run_dir) / "models" / "val_predictions.npy"
        if not pred_path.exists():
            raise FileNotFoundError(pred_path)

        pred_obj = np.load(pred_path, allow_pickle=True).item()
        array_key = spec["array_key"]
        if array_key not in pred_obj:
            array_key = spec.get("fallback_array_key", array_key)
        if array_key not in pred_obj:
            raise KeyError(f"{pred_path} has no array key {spec['array_key']}")
        pred = np.asarray(pred_obj[array_key], dtype=np.float64)
        gt = np.asarray(pred_obj.get("gt", np.full_like(pred, np.nan)), dtype=np.float64)

        input_len, output_len = infer_input_output_len(run_dir)
        step_len = STEP_LEN[dataset]
        df = load_dataframe(source_root / loc / "dataset_tp_sat.pkl")
        ts_to_meta, trace_meta = build_session_index(
            df,
            loc,
            max_gap_s=max_gap_s,
            min_len=min_len,
            train_ratio=train_ratio,
            calib_ratio=calib_ratio,
        )
        dataset_len = max(0, (len(df) - input_len - output_len) // step_len)
        train_size = int(0.8 * dataset_len)
        expected_val = dataset_len - train_size
        usable_rows = min(len(pred), expected_val)
        if usable_rows <= 0:
            raise ValueError(f"No usable validation windows for {predictor}/{dataset}")

        matched = 0
        kept = 0
        missing_trace_files = 0
        trace_counts = defaultdict(int)
        for pred_row_idx in range(usable_rows):
            window_idx = train_size + pred_row_idx
            output_start = window_idx * step_len + input_len
            if output_start >= len(df):
                continue
            ts = df["timestamp"].iloc[output_start]
            meta = ts_to_meta.get(timestamp_key(ts))
            if not meta:
                continue
            matched += 1
            split = meta["split"]
            if split not in splits:
                continue
            trace_id = meta["trace_id"]
            if not trace_file_exists(trace_root, loc, split, trace_id):
                missing_trace_files += 1
                continue

            safe_mbps, stats = choose_safe_cap_mbps(pred[pred_row_idx], horizon_quantile)
            if not math.isfinite(safe_mbps):
                continue
            gt_row = gt[pred_row_idx] if pred_row_idx < len(gt) else np.array([])
            gt_values = np.asarray(gt_row, dtype=np.float64)
            gt_values = gt_values[np.isfinite(gt_values)]
            gt_mean = float(np.mean(gt_values)) if gt_values.size else float("nan")
            gt_min = float(np.min(gt_values)) if gt_values.size else float("nan")
            risk_score = stats.get("horizon_pred_std_mbps", 0.0) / max(
                stats.get("horizon_pred_p50_mbps", safe_mbps),
                1.0,
            )
            rows.append(
                {
                    "predictor": predictor,
                    "dataset": dataset,
                    "loc": loc,
                    "split": split,
                    "trace_id": trace_id,
                    "session_idx": meta["session_idx"],
                    "time_s": f"{meta['time_s']:.6f}",
                    "chunk_idx": min(max(int(round(meta["time_s"] / 4.0)), 0), 47),
                    "safe_cap_kbps": f"{max(safe_mbps * 1000.0, 1.0):.6f}",
                    "risk_score": f"{risk_score:.6f}",
                    "window_idx": window_idx,
                    "val_prediction_idx": pred_row_idx,
                    "output_start_raw_idx": output_start,
                    "array_key": array_key,
                    "horizon_quantile": horizon_quantile,
                    "horizon_gt_mean_mbps": f"{gt_mean:.6f}",
                    "horizon_gt_min_mbps": f"{gt_min:.6f}",
                    "run_dir": run_dir,
                    **{key: f"{value:.6f}" for key, value in stats.items()},
                }
            )
            kept += 1
            trace_counts[trace_id] += 1

        split_counts = defaultdict(int)
        for trace_id, meta in trace_meta.items():
            if meta["split"] in splits:
                split_counts[meta["split"]] += 1

        covered_traces = set(trace_counts)
        target_traces = {
            trace_id
            for trace_id, meta in trace_meta.items()
            if meta["split"] in splits
            and trace_file_exists(trace_root, loc, meta["split"], trace_id)
        }
        summary_rows.append(
            {
                "predictor": predictor,
                "dataset": dataset,
                "loc": loc,
                "run_dir": run_dir,
                "array_key": array_key,
                "input_len": input_len,
                "output_len": output_len,
                "step_len": step_len,
                "raw_points": len(df),
                "dataset_windows": dataset_len,
                "expected_val_windows": expected_val,
                "prediction_rows": len(pred),
                "usable_prediction_rows": usable_rows,
                "matched_windows": matched,
                "exported_rows": kept,
                "missing_trace_files": missing_trace_files,
                "target_trace_count": len(target_traces),
                "covered_trace_count": len(covered_traces),
                "coverage": len(covered_traces) / max(len(target_traces), 1),
                "split_trace_counts": json.dumps(dict(sorted(split_counts.items()))),
            }
        )

    return rows, summary_rows


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary-dir",
        type=Path,
        default=repo_root / "data" / "starnet_model_summary",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        default=repo_root / "data" / "starnet_pkl",
    )
    parser.add_argument(
        "--trace-root",
        type=Path,
        default=repo_root / "safesabr" / "video_trace" / "trace" / "starlink",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=repo_root / "safesabr" / "experiment_logs" / "starlink_high" / "predictor_safe_caps",
    )
    parser.add_argument(
        "--predictors",
        default="StarNet-budget-scale,BG-CFQS,StarNet-point,XGBoost-budget-scale",
    )
    parser.add_argument("--splits", default="calib,test")
    parser.add_argument("--horizon-quantile", type=float, default=0.30)
    parser.add_argument("--max-gap-s", type=float, default=2.5)
    parser.add_argument("--min-len", type=int, default=120)
    parser.add_argument("--train-ratio", type=float, default=0.7)
    parser.add_argument("--calib-ratio", type=float, default=0.15)
    args = parser.parse_args()

    predictors = [item.strip() for item in args.predictors.split(",") if item.strip()]
    splits = {item.strip() for item in args.splits.split(",") if item.strip()}
    all_rows: list[dict] = []
    all_summary: list[dict] = []
    args.out_dir.mkdir(parents=True, exist_ok=True)

    for predictor in predictors:
        rows, summary_rows = export_predictor(
            predictor,
            args.summary_dir,
            args.source_root,
            args.trace_root,
            args.horizon_quantile,
            splits,
            args.max_gap_s,
            args.min_len,
            args.train_ratio,
            args.calib_ratio,
        )
        rows = sorted(
            rows,
            key=lambda row: (
                row["predictor"],
                row["loc"],
                row["split"],
                row["trace_id"],
                float(row["time_s"]),
            ),
        )
        write_csv(args.out_dir / f"{predictor.replace('/', '_')}_safe_caps.csv", rows)
        all_rows.extend(rows)
        all_summary.extend(summary_rows)

    all_rows = sorted(
        all_rows,
        key=lambda row: (
            row["predictor"],
            row["loc"],
            row["split"],
            row["trace_id"],
            float(row["time_s"]),
        ),
    )
    write_csv(args.out_dir / "all_predictor_safe_caps.csv", all_rows)
    write_csv(args.out_dir / "safe_cap_export_summary.csv", all_summary)
    with (args.out_dir / "safe_cap_export_config.json").open("w") as f:
        json.dump(
            {
                "summary_dir": str(args.summary_dir),
                "source_root": str(args.source_root),
                "trace_root": str(args.trace_root),
                "predictors": predictors,
                "splits": sorted(splits),
                "horizon_quantile": args.horizon_quantile,
                "max_gap_s": args.max_gap_s,
                "min_len": args.min_len,
                "train_ratio": args.train_ratio,
                "calib_ratio": args.calib_ratio,
            },
            f,
            indent=2,
            sort_keys=True,
        )

    print("Predictor safe-cap export complete")
    print(f"rows: {len(all_rows)}")
    print(f"out_dir: {args.out_dir}")
    print(f"summary: {args.out_dir / 'safe_cap_export_summary.csv'}")


if __name__ == "__main__":
    main()
